global_config:
  cmake_envs:
    CMAKE_CXX_COMPILER: "g++-7"
    MMDEPLOY_BUILD_SDK: "ON"
    MMDEPLOY_BUILD_SDK_MONOLITHIC: "ON"
    MMDEPLOY_SHARED_LIBS: "OFF"
    OpenCV_DIR: "${OpenCV_DIR}"

local_configs:
  - BUILD_NAME: "mmdeploy-{mmdeploy_v}-{system}-{machine}-onnxruntime{ort_v}"
    cmake_envs:
      MMDEPLOY_TARGET_DEVICES: '"cpu"'
      MMDEPLOY_TARGET_BACKENDS: "ort"
      ONNXRUNTIME_DIR: "${ONNXRUNTIME_DIR}"
  - BUILD_NAME: "mmdeploy-{mmdeploy_v}-{system}-{machine}-cuda{cuda_v}-tensorrt{trt_v}"
    cmake_envs:
      MMDEPLOY_TARGET_DEVICES: '"cuda"'
      MMDEPLOY_TARGET_BACKENDS: "trt"
      TENSORRT_DIR: "${TENSORRT_DIR}"
      CUDA_TOOLKIT_ROOT_DIR: "${CUDA_TOOLKIT_ROOT_DIR}"
      CUDNN_DIR: "${CUDNN_DIR}"
      pplcv_DIR: ${pplcv_DIR}/cuda-build/install/lib/cmake/ppl
